#!/usr/bin/env python3
"""
analyze_localization.py -- characterization artifact for the held-out run's
detection/localization relationship, built under the binding rule of
DEVIATION_LOG_v8 L17: harness semantics are QUOTED from source, never
summarized; all scoring goes through the harness's own public score_trial;
derived expectations are checked against the harness before anything is
asserted.

Reads demo/results_heldout_20260705T133553Z.json, regenerates ground truths
chain-major (the certified protocol of HELDOUT_RUN_LOG E5), re-certifies all
published per-cell figures with PASS/FAIL gates, and only then prints:
  Section 1  the four scoring functions, verbatim (inspect.getsource)
  Section 2  consistency certification against the published columns
  Section 3  detected-but-not-localized rows (full detections, with classes)
  Section 4  localized-but-not-detected rows (the wedge)
  Section 5  per-cell counts and the overlap accounting

Writes demo/analysis_localization_for_20260705T133553Z.txt and prints the
same to stdout. If any certification line reads FAIL, sections 3-5 are void.
"""

import hashlib
import inspect
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import score
from score import score_trial, Tally
from generate import generate_clean_chains
from inject import INJECTORS, ERROR_CLASSES

RESULT = "results_heldout_20260705T133553Z.json"
OUT = "analysis_localization_for_20260705T133553Z.txt"

CELLS = ["descriptive", "minimal", "minimal_plus_caution", "strict", "precision"]
# Published column values (record: results file, PANEL_READOUT_v8.3 cluster B,
# laptop confirmations of 2026-07-07). Used only as certification targets.
PUBLISHED = {
    "descriptive":          {"det": 0.933, "loc": 0.800, "fp": 1.000},
    "minimal":              {"det": 0.800, "loc": 0.600, "fp": 0.267},
    "minimal_plus_caution": {"det": 0.467, "loc": 0.333, "fp": 0.000},
    "strict":               {"det": 0.867, "loc": 0.467, "fp": 0.000},
    "precision":            {"det": 0.333, "loc": 0.267, "fp": 0.000},
}


def sha(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def main():
    lines = []
    say = lambda s="": (lines.append(s), print(s))

    say("Localization characterization for %s" % RESULT)
    say("Generated by analyze_localization.py under DEVIATION_LOG_v8 L17 rules.")
    say("Governing hashes at runtime:")
    for name in ("score.py", "inject.py", "generate.py"):
        say("  %-12s %s" % (name, sha(os.path.join(HERE, name))))
    say()

    say("=" * 72)
    say("SECTION 1 -- scoring criterion, quoted verbatim from score.py")
    say("=" * 72)
    for fn in (score.score_trial, score._matches_presence, score._matches_localization, score.Tally):
        say(inspect.getsource(fn))

    d = json.load(open(os.path.join(HERE, RESULT), encoding="utf-8"))
    chains = generate_clean_chains(3, seed=260706)
    gts = {}
    for c in chains:                      # chain-major: the certified order (E5)
        for cls in ERROR_CLASSES:
            gts[(c["chain_id"], cls)] = INJECTORS[cls](c)[1]

    recs = [r for r in d["records"] if r["set"] == "injected" and r["status"] == "ok"]
    clean = [r for r in d["records"] if r["set"] == "clean" and r["status"] == "ok"]
    n_excluded = sum(1 for r in d["records"] if r["status"] != "ok")

    scored = []
    tallies = {c: Tally() for c in CELLS}
    for r in recs:
        g = gts[(r["chain_id"], r["gt_class"])]
        s = score_trial(r["detections"], g)
        scored.append((r, g, s))
        tallies[r["cell"]].add(s)
    for r in clean:
        tallies[r["cell"]].add(score_trial(r["detections"], None))

    say("=" * 72)
    say("SECTION 2 -- certification against published columns (gate for 3-5)")
    say("=" * 72)
    say("records: %d injected ok, %d clean ok, %d excluded" % (len(recs), len(clean), n_excluded))
    all_pass = True
    for c in CELLS:
        det, loc, fp = (round(x, 3) for x in tallies[c].rates())
        p = PUBLISHED[c]
        ok = (det, loc, fp) == (p["det"], p["loc"], p["fp"])
        all_pass &= ok
        say("%-22s recomputed det/loc/fp %.3f/%.3f/%.3f  published %.3f/%.3f/%.3f  %s"
            % (c, det, loc, fp, p["det"], p["loc"], p["fp"], "PASS" if ok else "FAIL"))
    say("CERTIFICATION: %s" % ("ALL PASS" if all_pass else "FAILURE -- sections 3-5 are VOID"))
    say()

    if all_pass:
        say("=" * 72)
        say("SECTION 3 -- detected but NOT localized (score_trial verdicts)")
        say("=" * 72)
        for r, g, s in scored:
            if s["detected"] and not s["localized"]:
                say("%-22s %-16s gt (%s, %s)" % (r["cell"], r["gt_class"], g["hop"], g["item"]))
                say("    detections: %s" % [(x["error_class"], x["hop"], x["item"]) for x in r["detections"]])
        say()

        say("=" * 72)
        say("SECTION 4 -- localized but NOT detected (the wedge)")
        say("=" * 72)
        any_wedge = False
        for r, g, s in scored:
            if s["localized"] and not s["detected"]:
                any_wedge = True
                say("%-22s %-16s gt (%s, %s)" % (r["cell"], r["gt_class"], g["hop"], g["item"]))
                say("    detections: %s" % [(x["error_class"], x["hop"], x["item"]) for x in r["detections"]])
        if not any_wedge:
            say("(none)")
        say()

        say("=" * 72)
        say("SECTION 5 -- per-cell overlap accounting (15 injected trials each)")
        say("=" * 72)
        say("%-22s %9s %9s %11s %11s %9s" % ("cell", "detected", "localized", "det&loc", "det-only", "loc-only"))
        for c in CELLS:
            rows = [(r, g, s) for r, g, s in scored if r["cell"] == c]
            det = sum(1 for _, _, s in rows if s["detected"])
            loc = sum(1 for _, _, s in rows if s["localized"])
            both = sum(1 for _, _, s in rows if s["detected"] and s["localized"])
            say("%-22s %9d %9d %11d %11d %9d" % (c, det, loc, both, det - both, loc - both))
        say()
        say("Note: 'localized' does not imply 'detected' under score_trial; the")
        say("columns above state the actual relationship for this run.")

    with open(os.path.join(HERE, OUT), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("\nwrote %s" % os.path.join("demo", OUT))


if __name__ == "__main__":
    main()
